### Default config for all projects
gpm:
  host: "127.0.0.1"
  port: 4760
  read_buffer_size: 1024
adc:
  inner_read_buffer_size: 2000
  outer_read_buffer_size: 2000
  mock_reader_state_buffer_size: 100
  sleep_between_reads_in_seconds: 0.1
processing:
  sleep_between_processing_in_seconds: 5
metrics:
  port: 9998
log:
  formatters:
    color_format:
      class: colorlog.ColoredFormatter
      format: "%(asctime)s [%(log_color)s%(levelname)s%(reset)s] [%(bold)s%(process)d:%(threadName).12s%(reset)s] %(bold_blue)s%(name)s%(reset)s - %(message)s"
      style: "%"
    standard_format:
      format: "%(asctime)s [%(levelname)s] [%(process)d:%(threadName).12s] %(name)s - %(message)s"
      style: "%"
  handlers:
    console_handler:
      class: logging.StreamHandler
      formatter: color_format
      stream: "ext://sys.stdout"
  loggers:
    "":
      level: INFO
      handlers: [console_handler]