# TCP configs
GPM_HOST="127.0.0.1"
GPM_PORT=4760
READ_BUF_SIZE=1024

# SGCP constants
# TODO: @krarpit figure out a way to derive these 
# from proto files
PREFIX_LENGTH_SIZE=8
MAESTRO_RESOURCE="MAESTRO"
MAESTRO_OPEN_FIST="OPEN_FIST"
MAESTRO_CLOSE_FIST="CLOSE_FIST"